language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libglib2.0 libglib2.0-dev libjansson4 libjansson-dev libopenmpi-dev openmpi-bin libopenmpi-dev
script:
  - which mpicc
  - locate mpicc
  - ./configure --with-cc=mpicc && cd build && make -j 2 
#&& make CTEST_OUTPUT_ON_FAILURE=1 test && true

